serial_port: /dev/ttySERVO
baud_rate: 1000000

use_mock: false
use_sync_write: true

pan_motor_id: 1
tilt_motor_id: 2

pan_center_steps: 2048
tilt_center_steps: 2646

sts_max_velocity_steps: 3400
proportional_vel_max: 0

pan_joint_lower: -1.5708
pan_joint_upper: 1.5708
tilt_joint_lower: -1.5708
tilt_joint_upper: 1.5708
